saved: true
channels:
  nicolive:
    - serviceId: 3273601024
      channelId: ch2646436
      enabled: true
  nx-jikkyo:
    - serviceId: 3273601024
      channelId: jk101
      enabled: true
suggestions:
  nicolive:
    "3273601024": ch2646436
  nx-jikkyo:
    "3273601024": jk101
