/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/keyword-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * キーワード録画ルール一覧の取得。
         * @description 登録済みのキーワード自動録画ルールを一覧で取得する。
         *
         *     有効と停止の両方を含み、登録日時の昇順で返す。
         */
        get: operations["getKeywordRules"];
        put?: never;
        /**
         * キーワード録画ルールの登録。
         * @description キーワード自動録画ルールを登録する。
         *
         *     登録に成功すると `id` と `createdAt` を採番し、自動予約ジョブの再実行を予約する。
         */
        post: operations["postKeywordRules"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keyword-rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * キーワード録画ルールの更新。
         * @description キーワード自動録画ルールを更新する。
         *
         *     有効と停止のトグルを含め、全項目を入力で上書きする。更新に成功すると自動予約ジョブの再実行を予約する。
         */
        put: operations["putKeywordRulesId"];
        post?: never;
        /**
         * キーワード録画ルールの削除。
         * @description キーワード自動録画ルールを削除する。
         *
         *     登録済みの予約は取り消さない。削除では自動予約ジョブの再実行を予約しない。
         */
        delete: operations["deleteKeywordRulesId"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 通知設定の取得。
         * @description ntfy への通知設定を取得する。
         *
         *     未保存の場合は通知をすべて無効にした既定値を返す。`token` は平文で返す。
         */
        get: operations["getNotificationSettings"];
        /**
         * 通知設定の保存。
         * @description ntfy への通知設定を保存する。
         *
         *     全項目を入力で上書きする。イベントのトグルが 1 つでも有効な場合は `url` が必須となる。
         */
        put: operations["putNotificationSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification-settings/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * テスト通知の送信。
         * @description テスト通知を送信する。
         *
         *     保存前の入力値である `url` と `token` を受け取り、実際に ntfy へ送信する。送信に失敗した場合は 502 を返す。
         */
        post: operations["postNotificationSettingsTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description キーワード自動録画のルール。
         *
         *     一致した未予約かつ将来の番組を定期ジョブが自動で予約する。
         */
        KeywordRule: {
            /**
             * Format: uuid
             * @description ルールの識別子。
             */
            id: string;
            /**
             * @description 番組名に対して部分一致させるキーワード。大文字小文字は区別しない。
             * @example 大相撲
             */
            keyword: string;
            /**
             * Format: date
             * @description 期間の開始日。ローカル日付で両端を含む。未指定は無制限。
             * @example 2026-01-01
             */
            from?: string;
            /**
             * Format: date
             * @description 期間の終了日。ローカル日付で両端を含む。未指定は無制限。
             * @example 2026-01-31
             */
            to?: string;
            /** @description 対象サービスの Mirakurun service id の配列。空配列は全チャンネルを表す。 */
            serviceIds: number[];
            /** @description 対象ジャンルの ARIB lv1 コード (0 から 15) の配列。空配列は全ジャンルを表す。 */
            genres: number[];
            /** @description 有効か停止か。停止中は自動予約の対象から外れる。 */
            enabled: boolean;
            /**
             * Format: int64
             * @description 登録日時。epoch ミリ秒。
             */
            createdAt: number;
        };
        /**
         * @description キーワード自動録画ルールの登録および更新の入力。
         *
         *     サーバが採番する `id` と `createdAt` を除いた項目で構成する。
         */
        KeywordRuleInput: {
            /**
             * @description 番組名に対して部分一致させるキーワード。大文字小文字は区別しない。
             * @example 大相撲
             */
            keyword: string;
            /**
             * Format: date
             * @description 期間の開始日。ローカル日付で両端を含む。未指定は無制限。
             * @example 2026-01-01
             */
            from?: string;
            /**
             * Format: date
             * @description 期間の終了日。ローカル日付で両端を含む。未指定は無制限。
             * @example 2026-01-31
             */
            to?: string;
            /** @description 対象サービスの Mirakurun service id の配列。空配列は全チャンネルを表す。 */
            serviceIds: number[];
            /** @description 対象ジャンルの ARIB lv1 コード (0 から 15) の配列。空配列は全ジャンルを表す。 */
            genres: number[];
            /** @description 有効か停止か。停止中は自動予約の対象から外れる。 */
            enabled: boolean;
        };
        /**
         * @description ntfy への録画イベント通知の設定。
         *
         *     各イベントのトグルが 1 つでも有効な場合は `url` が必須となる。
         */
        NotificationSettings: {
            /**
             * @description トピックまで含む ntfy の URL。
             * @example https://ntfy.sh/mirakc-rec
             */
            url: string;
            /** @description アクセストークン。空文字は未設定を表す。Authorization ヘッダの Bearer として送信する。 */
            token: string;
            /** @description 録画予約の登録 (キーワード自動録画と手動) を通知するか。 */
            onSchedule: boolean;
            /** @description 録画開始を通知するか。 */
            onStart: boolean;
            /** @description 録画終了を通知するか。 */
            onEnd: boolean;
            /** @description 録画失敗を通知するか。 */
            onFail: boolean;
            /** @description 録画予約の削除を通知するか。 */
            onRemove: boolean;
        };
        /**
         * @description テスト通知の送信先。
         *
         *     保存前の入力値をそのまま受け取り、実際に ntfy へ送信する。
         */
        NotificationTestRequest: {
            /**
             * @description トピックまで含む ntfy の URL。
             * @example https://ntfy.sh/mirakc-rec
             */
            url: string;
            /** @description アクセストークン。空文字は未設定を表す。Authorization ヘッダの Bearer として送信する。 */
            token: string;
        };
        NotificationTestResponse: {
            /**
             * @description テスト通知の送信に成功したことを表す。
             * @constant
             */
            ok: true;
        };
        ResponseError: {
            /**
             * @description エラーの内容を表すメッセージ。
             * @example keyword must be a non-empty string
             */
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getKeywordRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 処理成功時。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordRule"][];
                };
            };
        };
    };
    postKeywordRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 登録するルール。 */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["KeywordRuleInput"];
            };
        };
        responses: {
            /** @description 登録成功時。採番後のルールを返す。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordRule"];
                };
            };
            /** @description 入力が不正な場合。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseError"];
                };
            };
        };
    };
    putKeywordRulesId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ルールの識別子。 */
                id: string;
            };
            cookie?: never;
        };
        /** @description 上書きするルール。全項目を置き換える。 */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["KeywordRuleInput"];
            };
        };
        responses: {
            /** @description 更新成功時。更新後のルールを返す。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordRule"];
                };
            };
            /** @description 入力が不正な場合。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseError"];
                };
            };
            /** @description 対象のルールが存在しない場合。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseError"];
                };
            };
        };
    };
    deleteKeywordRulesId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ルールの識別子。 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除成功時。レスポンスボディは持たない。 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 対象のルールが存在しない場合。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseError"];
                };
            };
        };
    };
    getNotificationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 処理成功時。未保存の場合は既定値を返す。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettings"];
                };
            };
        };
    };
    putNotificationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 保存する設定。全項目を上書きする。 */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NotificationSettings"];
            };
        };
        responses: {
            /** @description 保存成功時。保存後の設定を返す。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettings"];
                };
            };
            /** @description 入力が不正な場合。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseError"];
                };
            };
        };
    };
    postNotificationSettingsTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 送信先。保存前の入力値を受け取る。 */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NotificationTestRequest"];
            };
        };
        responses: {
            /** @description 送信成功時。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationTestResponse"];
                };
            };
            /** @description 入力が不正な場合。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseError"];
                };
            };
            /** @description ntfy への送信に失敗した場合。 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseError"];
                };
            };
        };
    };
}
