// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_mirakc_path_ from "./routes/api/mirakc/[...path].ts";
import * as $api_web_push_subscribe_publicKey_ from "./routes/api/web-push/subscribe/[publicKey].ts";
import * as $api_web_push_subscribe_key from "./routes/api/web-push/subscribe/key.ts";
import * as $index from "./routes/index.tsx";
import * as $program_index from "./routes/program/index.tsx";
import * as $recording_index from "./routes/recording/index.tsx";
import * as $search_index from "./routes/search/index.tsx";
import * as $Program from "./islands/Program.tsx";
import * as $Recording from "./islands/Recording.tsx";
import * as $Search from "./islands/Search.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/mirakc/[...path].ts": $api_mirakc_path_,
    "./routes/api/web-push/subscribe/[publicKey].ts":
      $api_web_push_subscribe_publicKey_,
    "./routes/api/web-push/subscribe/key.ts": $api_web_push_subscribe_key,
    "./routes/index.tsx": $index,
    "./routes/program/index.tsx": $program_index,
    "./routes/recording/index.tsx": $recording_index,
    "./routes/search/index.tsx": $search_index,
  },
  islands: {
    "./islands/Program.tsx": $Program,
    "./islands/Recording.tsx": $Recording,
    "./islands/Search.tsx": $Search,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
